Fix: Add Cookie onChange Listener to Recalculate Cookie Attributes
GoogleChromeLabs/ps-analysis-tool pull request #77
Opened 2023-07-21 05:41 UTC by mayan-000

## Description

This pull request aims to address an issue related to the calculation of cookie attributes. Previously, the attributes were not automatically updated when changes occurred in the cookies. This PR adds a onChange listener to cookies, ensuring that the attributes are recalculated whenever there is a modification to the cookies.

## Relevant Technical Choices
-  Implements a new `chrome.cookies.onChanged` listener to actively monitor any changes that occur in the Cookie Store. This listener will capture events for cookie deletion, updates, and new cookie set actions. 
Subsequently, the listener triggers updates to the corresponding cookie attributes in real-time.

## Testing Instructions
- Launch the Google Chrome browser.
- Navigate to settings and ensure third-party cookies are blocked.
- Visit any website designed to set third-party cookies.
- Access the Developer Tools and navigate to the Privacy Sandbox.
- Verify the statuses of "Cookie Set" and "IBC Compliant" (they should be correct at this stage).
- Keep the current tab active, and simultaneously open another tab to access the settings again. Here, change the setting to allow third-party cookies.
- Return to the original tab (the one with the third-party cookies) and refresh the page.
- Upon the refresh, the Cookie Set and IBC Compliant status would have been updated.
- Open the settings in a separate tab again, and revert to blocking third-party cookies.
- Go back to the original tab and refresh the page. Make sure the cookie being tested is not present in Applications tab.
- The Cookie Set and IBC complaint values will be updated according to cookie values, showing cookie is not set.

## Additional Information:

## Screenshot/Screencast

https://github.com/GoogleChromeLabs/ps-analysis-tool/assets/58820001/00604c42-b240-4d4c-8f8d-4782fc44135e

---

Fixes #76

2023-07-24 19:03 UTC, gagan0123 commented
Thanks for the PR.
I can confirm this resolves the issue #76

2023-07-25 01:50 UTC, sayedtaqui requested changes

2023-07-25 01:50 UTC, sayedtaqui commented on packages/extension/src/view/devtools/components/tabContent/cookies/components/cookieDetails.tsx
> +    calculateCookieAttributes();
Please handle Promise returned from calculateCookieAttributes

2023-07-25 15:16 UTC, mayan-000 commented
Closing this PR.
As @ayushnirwal will be moving this PR's logic of `Cookie Set` and `IBC Compliance` to stateProviders aligning with the Tabular UI in Issue #75.

cc: @sayedtaqui @gagan0123

2023-07-25 15:16 UTC, closed without merging