Feature: Interest groups bubble plotting
GoogleChromeLabs/ps-analysis-tool pull request #865
Opened 2024-11-04 11:12 UTC by amovar18

## Description
In this PR, we aim to create a container for interest group bubbles. So that it looks better when there are more number of interest group bubbles.

## Relevant Technical Choices
- A new module `bubbles` has been added. This module will manage the animation for the loading the interest group and joining interest group.
- this will also manage the expansion and minification of the interest group bubble container.

## Testing Instructions
- Clone the branch.
- In the terminal run `cd ee && npm i && npm run start`.
- Now open https://localhost:8080/index.html.
- Once interest group is added by advertiser you can click on this and expand the circle to see interest groups.

## Additional Information:

## Screenshot/Screencast

![Screenshot 2024-11-04 at 16 34 55](https://github.com/user-attachments/assets/bf261f51-8d74-4547-bd05-4f8f08209f98)

https://github.com/user-attachments/assets/2fe99e76-2c28-4cb6-8bd2-84c7507bccb2

---

## Checklist

- [x] I have thoroughly tested this code to the best of my abilities.
- [x] I have reviewed the code myself before requesting a review.
- [x] This code is covered by unit tests to verify that it works as intended.
- [x] The QA of this PR is done by a member of the QA team (to be checked by QA).

2024-11-11 16:48 UTC, mohdsayed commented
@amovar18 I think closing the bubble on play button is not intuitive enough. We should probably add any other icon indicating how the bubble will expand and close.

<img width="1278" alt="image" src="https://github.com/user-attachments/assets/6829bd48-dcb5-40df-9c4c-e6943646e3ae">

2024-11-11 17:13 UTC, mohdsayed commented
3. The number is not very visible when there are multiple color bubbles.
<img width="82" alt="image" src="https://github.com/user-attachments/assets/2b9a5554-37a3-4e1e-9e5a-716b2ed32d4e">

2024-11-11 17:16 UTC, mohdsayed commented
4. When the circle doesn't not have any bubble yet, and circle expands, it first goes to the left and then in the center

2024-11-11 17:18 UTC, mohdsayed commented
5. Some bubbles are so small that they are not readable ( laptop in this case )
<img width="659" alt="image" src="https://github.com/user-attachments/assets/2cc57e68-7fee-4566-a008-9f9a47791ed1">

2024-11-11 17:19 UTC, mohdsayed commented
6. Since the bubble are clickable, the cursor should change when hovering over it.

2024-11-11 17:21 UTC, mohdsayed commented on ee/src/config.js
> +          'wJk91XxpVnFvc2oySFZtdjFaQmxzV3U1ODdnPT18',
Let's use some name instead of ID.

2024-11-11 17:25 UTC, mohdsayed requested changes
Looks good, just few small improvements are required.

2024-11-11 17:30 UTC, mohdsayed commented
7. I was thinking maybe we could add a subtle overlay in the background. When the circle expands, it would appear more focused.

2024-11-13 04:53 UTC, amovar18 commented on ee/src/config.js
> +          'wJk91XxpVnFvc2oySFZtdjFaQmxzV3U1ODdnPT18',
Fixed in latest commits.

2024-11-13 04:53 UTC, amovar18 commented
@mohdsayed fixed the UX issues in latest commits.

2024-11-14 08:58 UTC, mohdsayed commented
@amovar18 one of the build is failing.

2024-11-14 09:15 UTC, amovar18 commented
Fixed the linting test.

2024-11-15 03:29 UTC, mohdsayed commented
Some more improvements are required.

- [ ]  Remove blur from small circle.
- [ ]  Make expand and collapse icons grey.
- [ ]  Move collapse icon closer to the larger circle.
- [ ]  Close on ESC key press and when clicking outside the larger circle.
- [ ]  Use grey color for both small and large circles.
- [ ]  Change cursor to pointer for all clickable circles.
- [ ]  Fix issue where expand and collapse icons appear after a quick refresh.

2024-11-15 08:23 UTC, mohdsayed commented
@amovar18 Two issues are still pending

https://github.com/GoogleChromeLabs/ps-analysis-tool/pull/865#issuecomment-2477881487

2024-11-18 04:50 UTC, mohdsayed commented on packages/explorable-explanations/public/index.html
> +
As the CSS is growing, we should soon move it to a css file.

2024-11-18 06:43 UTC, mohdsayed commented on packages/explorable-explanations/src/lib/bubbles.js
> +/*
Moving this to module as it encapsulates functional unit of the application, responsible for a specific feature.

2024-11-18 07:04 UTC, mohdsayed approved these changes
Looks great

2024-11-18 07:04 UTC, merged